spring:
  datasource:
    driverClassName: com.impossibl.postgres.jdbc.PGDriver
    url: jdbc:pgsql://localhost:5432/terraria_server_web_dev
    username: ${TSW_DB_USERNAME:tswdev}
    password: ${TSW_DB_PASSWORD}
  flyway:
    enabled: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL82Dialect
    hibernate:
      ddl-auto: validate
