spring:
  datasource:
    driverClassName: com.impossibl.postgres.jdbc.PGDriver
    url: jdbc:pgsql://localhost:5432/terraria_server_web
    username: ${TSW_DB_USERNAME:tswlocal}
    password: ${TSW_DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL82Dialect
    hibernate:
      ddl-auto: update
