spring:
  resources:
    static-locations: file:./frontend/dist/terraria-server-web/
    chain:
      # live-frontend is meant for rapid frontend development so caching would be bad.
      cache: false
