spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/terraria_server_web
    driverClassName: org.postgresql.Driver
    username: ${TSW_DB_USERNAME:tswlocal}
    password: ${TSW_DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL82Dialect
    hibernate:
      ddl-auto: update
